# Generated by Django 3.0.5 on 2020-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='photo',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
        migrations.AddField(
            model_name='movies',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='originaltitle',
            field=models.CharField(max_length=129, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.DateTimeField(null=True),
        ),
    ]
